[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino

; Prędkość portu szeregowego
monitor_speed = 115200

; Biblioteki, które PlatformIO pobierze za nas automatycznie
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1    ; Nowy, lekki stos BLE
    adafruit/Adafruit BMP3XX Library @ ^2.1.2  ; Barometr
    adafruit/Adafruit LSM6DS @ ^4.7.0 ; Akcelerometr
    olikraus/U8g2 @ ^2.34.22          ; Wyświetlacz OLED

; Optymalizacje pamięci i flagi kompilatora
build_flags = 
    -D CORE_DEBUG_LEVEL=0